
PUT http://localhost:8080/books/104
Content-Type: application/json

{
      "id":104,  
    "title":"MATLAB",
    "author":"Rajkaml",
    "discription":"Useful in Sigal Processing",
    "price":812
}