POST http://localhost:8080/login
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "1234"
}

### 
GET http://localhost:8080/books
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX1VTRVIiLCJleHAiOjE3ODk0NjIzMzR9.cy95T0LtNImodqB1u6bbdg14H38KmK7krco3PE6E1bo

